### ISSUE TITLE
Problem reading file

### ISSUE THREAD

**Issue by MariaLuizaF** [DisciplinasProgramacao/poo_tp_manha-grupo-madm#2]
Boa noite @joaocaram  , meu grupo e eu estamos um pouco com duvida no momento de leitura do arquivo no main , pois ele esta no método dentro da classe de leitura de arquivo . Sera que estamos efetuando corretamente essa ligação ? 
Segue abaixo a foto do código do método  e do main 

![image](https://github.com/DisciplinasProgramacao/poo_tp_manha-grupo-madm/assets/103125164/c4f3ec9e-375c-4d09-a6b8-7d8f32acbe7d)
![image](https://github.com/DisciplinasProgramacao/poo_tp_manha-grupo-madm/assets/103125164/31b30f33-0c73-4434-b232-0a3ed6bae307)

obs: caso tenha problema em abrir as fotos so me avisar que penso em alguma forma de enviar novamente. 
uma boa noite , abraço!!

**Comment by MariaLuizaF** [comment]
@joaocaram  fechei o problema que não tinha dados , este aqui no qual tem foto é o real problema que estou com duvida .

**Comment by joaocaram** [comment]
Luiza, você pode referenciar o  [arquivo diretamente](https://github.com/DisciplinasProgramacao/poo_tp_manha-grupo-madm/blob/master/codigo/trabalhoSegundaIteracao.zip)
