### ISSUE TITLE
Problema na Leitura do Arquivo 

### ISSUE THREAD

**Issue by MariaLuizaF** [DisciplinasProgramacao/poo_tp_manha-grupo-madm#3]
bom dia @joaocaram , estamos com duvida no endereçamento do arquivo ( Path Name ) . Fizemos as mudanças pedidas de list para map , avalie se esta correto por gentileza .
Segue abaixo as fotos do problema de arquivo ( os códigos entao no diretório -  codigo 3.0 )

[
![WhatsApp Image 2023-05-25 at 10 46 13](https://github.com/DisciplinasProgramacao/poo_tp_manha-grupo-madm/assets/103125164/ce7420ae-cdd3-4142-92da-5eb69aafbc68)
](url)

![WhatsApp Image 2023-05-25 at 10 45 25](https://github.com/DisciplinasProgramacao/poo_tp_manha-grupo-madm/assets/103125164/0f3de4fd-34cf-4458-8f9a-cc8a2f6cf0ef)
](url)

**Comment by joaocaram** [comment]
Oi, Maria Luiza. Este negócio de caminho de arquivos sempre é dor de
cabeça. Isso de criar pastas separadas para versão 2, versão 3 piora ainda
mais o problema (e não pode. Eu só vou corrigir o que estiver dentro do
Código). Enquanto não ajeitam isso, eu sugiro colocar uma ou mais variáveis
static para os nomes de arquivos lá em cima no App, depois cada pessoa que
for executar o sistema muda para o caminho no seu próprio dispositivo.
Quando vocês passarem o código para a pasta principal eu tento mostrar como
achar o arquivo.

AVISO: Esta mensagem é destinada exclusivamente à(s) pessoa(s) a quem é
dirigida e pode conter informação sigilosa e legalmente protegida. Caso não
seja o destinatário, favor notificar o remetente. Ficam proibidas a
utilização, divulgação, cópia e distribuição do seu conteúdo sem
autorização prévia do remetente.
